"""Reformat table

Revision ID: 7e3b7d56b420
Revises: 63cddc27defb
Create Date: 2024-06-27 12:58:59.388236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e3b7d56b420'
down_revision: Union[str, None] = '63cddc27defb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('task', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('task', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('task', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('ix_task_type', 'task', ['type'], unique=False)
    op.create_unique_constraint('uq_task_title', 'task', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_title', 'task', type_='unique')
    op.drop_index('ix_task_type', table_name='task')
    op.alter_column('task', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('task', 'updated_at')
    op.drop_column('task', 'created_at')
    # ### end Alembic commands ###
